### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [WhisperSystems/libsignal-protocol-c#10]
I would like to point out that identifiers like "[`__COMPARE_H__`](https://github.com/WhisperSystems/libsignal-protocol-c/blob/0640b5accaf207aa51fbf83a7d2cd389c2bd24ad/src/curve25519/ed25519/additions/compare.h#L1)" and "[`__ZEROIZE_H__`](https://github.com/WhisperSystems/libsignal-protocol-c/blob/0640b5accaf207aa51fbf83a7d2cd389c2bd24ad/src/curve25519/ed25519/additions/zeroize.h#L1)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by dkonigsberg** [comment]
The referenced code is part of the DJB curve25519 library, which is included as-is whenever possible. Please report any issues with that code, which are not fixes specific to the functionality of libsignal-protocol-c, to the upstream library maintainer.

**Comment by elfring** [comment]
How do you think about to [make any more identifiers standard compliant](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?
