### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [WhisperSystems/libsignal-protocol-c#11]
Would you like to replace more defines for constant values by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages) to stress their relationships?
* [AX_ERR_…](https://github.com/WhisperSystems/libsignal-protocol-c/blob/e643d623eb3d2f61a2940bb4545409c0d0092e13/src/axolotl.h#L21)
* [CIPHERTEXT_…_TYPE](https://github.com/WhisperSystems/libsignal-protocol-c/blob/a91cf1eb9e32cc1ce4c812bea8bbdb8c1bf356d2/src/protocol.h#L19)

**Comment by moxie0** [comment]
Thanks @elfring, but we don't use GitHub for discussion or Q&A.  For more information about how we use GH, you can look here: https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md#issue-tracker-is-for-bugs
