### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [WhisperSystems/libsignal-protocol-c#12]
Would you like to [replace any double quotes](https://github.com/WhisperSystems/libsignal-protocol-c/blob/e643d623eb3d2f61a2940bb4545409c0d0092e13/src/axolotl.h#L8 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by moxie0** [comment]
Same
