### ISSUE TITLE
Clearing the confusion about one-time prekeys; are they necessary? 

### ISSUE THREAD

**Issue by kewde** [WhisperSystems/libsignal-protocol-c#23]
Hello,

I was wondering if someone could clear the air about this issue before I dig into implementing the callback functions for the code. There is a bit of confusion about whether a one-time prekey bundle is required to create a session or not. [[1]](http://security.stackexchange.com/questions/121304/how-does-the-signal-protocol-used-by-whataapp-work/123939#123939)

Let's take the example from the README.MD, if we were to omit the following would the session creation still work? I'm currently under the assumption it would as that would align with the behavior as specified in technical whitepaper of whatsapp. [1](http://security.stackexchange.com/questions/121304/how-does-the-signal-protocol-used-by-whataapp-work/123939#123939)

`/* Build a session with a pre key retrieved from the server. */
session_builder_process_pre_key_bundle(builder, retrieved_pre_key);`

---

 Sessions are built from one of three different possible vectors:
 * - A session_pre_key_bundle retrieved from a server
 * - A pre_key_signal_message received from a client
 * - A key_exchange_message sent to or received from a client

I'm really interested in the procedure that is best described as a "a non-interactive one-time setup" such as using pre_key_signal_message as building block for a session but there are no test suites available for the functions used by two other vectors (aside from retrieving pre_key_bundle from a server). Not that those are necessary to comprehend the code, the required parameters and setup seem pretty straight forward. 

Untested function of interest:
```
int session_builder_process_pre_key_signal_message(session_builder *builder,
        session_record *record, pre_key_signal_message *message, uint32_t *unsigned_pre_key_id)
```

PS:
I haven't had the time to compile and play with it yet, would certainly yield the answers I seek but I thought this might be a valuable addition to the README or any documentation for that matter.

**Comment by moxie0** [comment]
Thanks @kewde but we don't use GH issues as a discussion forum. There are several unofficial OWS discussion forums on the internet that are more appropriate for Q&A, and you can also contact OWS support through the support center for questions.  Thanks.
