### ISSUE TITLE
Can't build shared library

### ISSUE THREAD

**Issue by drizt** [WhisperSystems/libsignal-protocol-c#32]
Error when linking shared library on Linux x86_64

```
$ cmake -DBUILD_SHARED_LIBS=ON ..
...
$ make
...
[100%] Linking C shared library libsignal-protocol-c.so
/usr/bin/ld: curve25519/CMakeFiles/curve25519.dir/ed25519/fe_isnonzero.c.o: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
curve25519/CMakeFiles/curve25519.dir/ed25519/fe_isnonzero.c.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
src/CMakeFiles/signal-protocol-c.dir/build.make:706: recipe for target 'src/libsignal-protocol-c.so' failed
make[2]: *** [src/libsignal-protocol-c.so] Error 1
CMakeFiles/Makefile2:91: recipe for target 'src/CMakeFiles/signal-protocol-c.dir/all' failed
make[1]: *** [src/CMakeFiles/signal-protocol-c.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by dkonigsberg** [comment]
Building as a shared library is not currently a tested or supported build configuration.  In most common use cases, this library is statically linked into the using application.

That being said, building as a shared library probably should be supported. However, doing so will likely require a combination of updates to the cmake config files and the public header files.

**Comment by drizt** [comment]
So maybe there is a sense to explicity set `STATIC` [here](https://github.com/WhisperSystems/libsignal-protocol-c/blob/master/src/CMakeLists.txt#L61)? And drop it in a future when shared library support will be added?
