### ISSUE TITLE
Need beginner tutorials for open whisper system

### ISSUE THREAD

**Issue by jeeva-sil** [WhisperSystems/libsignal-protocol-c#33]
Me and my team have developed chat application for ios, android and windows using xmpp server. Now we are planning to implement Whisper Systems in our application. Already i have searched all your libraries and application from GitHub but i want some beginner step by step documentation to implement Whisper Systems in our application.

**Comment by chrisballinger** [comment]
Are you aware of the licensing terms?

**Comment by moxie0** [comment]
Hey @jeeva-sil we're tracking documentation elsewhere, no need to track an issue for that here, but thanks.
