### ISSUE TITLE
Remove key exchange session builder code

### ISSUE THREAD

**Issue by mmdriley** [WhisperSystems/libsignal-protocol-c#40]
e.g. `session_builder_process_initiate`, `session_builder_process_response`

This was removed from libsignal-protocol-java in August 2016: https://github.com/WhisperSystems/libsignal-protocol-java/commit/f92517c82a92e79ade3551133f7d9a3f721ac8bc

**Comment by gkdr** [comment]
What is the reasoning behind this? That Signal doesn't use the synchronous key exchange?
I think it would be nice to have a maintained reference implementation of the double ratchet which is not asynchronous per se.

**Comment by mmdriley** [comment]
Since Signal doesn't use this, I don't think "maintained" was really an option. This code is either unmaintained or removed.

**Comment by gkdr** [comment]
Well, the Signal protocol doesn't have to be only what the Signal app uses, I thought.
I see this was done in d83a61a328d4e36bcccf9066c925b63bb75bf968 without further comment here.
Too bad, I was actually using that code.
