### ISSUE TITLE
Facebook Messenger

### ISSUE THREAD

**Issue by petermoresi** [WhisperSystems/libsignal-protocol-c#47]
Seems like Facebook is using this library (and the java version) in their messenger product.

https://fbnewsroomus.files.wordpress.com/2016/07/secret_conversations_whitepaper-1.pdf

Did WhisperSystem sell them a commercial license or did Facebook include GPL software in a closed source product?

**Comment by moxie0** [comment]
Hey @petermoresi this is an issue tracker, we don't use it as a discussion forum. If you have questions or discussion topics, check out the mailing list.
