### ISSUE TITLE
PQC

### ISSUE THREAD

**Issue by aaannndddyyy** [WhisperSystems/libsignal-protocol-c#49]
Please consider exploring  possible use of post-quantum crypto algorithms like NTRU and SIDH for signal protocol.

**Comment by dkonigsberg** [comment]
Hey @aaannndddyyy this is an issue tracker, we don't use it as a discussion forum. If you have questions or discussion topics, check out the mailing list.

**Comment by aaannndddyyy** [comment]
and where is that mailing list? Cant find it on your homepage

**Comment by dkonigsberg** [comment]
[Mailing List](https://lists.riseup.net/www/info/whispersystems)
[Discourse](https://whispersystems.discoursehosting.net/)

**Comment by aaannndddyyy** [comment]
thanks
