### ISSUE TITLE
Add option for PIC in static lib

### ISSUE THREAD

**Issue by gkdr** [WhisperSystems/libsignal-protocol-c#50]
I want to statically link this library into a shared library (it is actually a libpurple plugin, and I believe this is not an uncommon format for plugins in general).
In order to achieve this as it is, I added `-fPIC` to the makefile flags by hand, so I can't just reference this library e.g. by adding it as a submodule.

Could I ask you to add a target that generates PIC in an .a for more linking options? It would be greatly appreciated.
If such an option automatically exists through CMake (somehow), I would like to ask to put the different CMake options on the README - I dug through old closed issues to find the option for building a shared lib.

**Comment by dkonigsberg** [comment]
Adding the following argument to cmake should fix this for you:
`-DCMAKE_C_FLAGS=-fPIC`

**Comment by gkdr** [comment]
Thanks for the quick reply!
It did indeed fix this issue - I must have worded my internet searches weirdly when trying to find a solution like this.

I'm going to close this issue now, and I hope I didn't waste too much of your time.
(I still recommend putting the different build options on the README, though.)
