### ISSUE TITLE
intentional ignoring of message_version in signal_message_verify_mac?

### ISSUE THREAD

**Issue by Smattr** [WhisperSystems/libsignal-protocol-c#52]
The function `signal_message_verify_mac` takes a parameter `message_version`, but instead accesses the version through `message->message_version`. From what I can see, this is still correct because the only call of this function has these two values equal. However, it leads to a potentially misleading interface to this functionality. Is this a deliberate layout to support future extension?

**Comment by dkonigsberg** [comment]
Looking into this, I suspect there is really only one explanation. Blindly copying the interface of the [Java version](https://github.com/WhisperSystems/libsignal-protocol-java/blob/master/java/src/main/java/org/whispersystems/libsignal/protocol/SignalMessage.java) of this code, possibly fumbling a field reference (albeit in a meaningless way) in the process.

If you look at the Java version, you'll notice that it also uses that parameter in ways that don't entirely make sense.  I don't know if there was a legacy reason for this, or if it was a simple slip-up.  Regardless, it probably makes sense to put this on a to-do list of things in the library that needs cleanup.

**Comment by afriedmanGlacier** [comment]
I am having trouble receiving an OMEMO message in the latest version of ChatSecure, and in debugging, the error occurs in SignalProtocolC -> session_cipher.c. Every time, it gets to "Bad MAC" in signal_message_verify_mac, so it never ends up decrypting the message. Wondering if this is related to this change?

**Comment by sss123next** [comment]
same problem here, i am working on omemo for miranda-ng jabber, and having mac missmatch problem here https://github.com/WhisperSystems/libsignal-protocol-c/blob/master/src/protocol.c#L422, i am not completely sure what this is libsignal bug, looks very similar to described by afriedmanGlacier problem for me, as result of this problem i have SG_ERR_INVALID_MESSAGE from session_cipher_decrypt_pre_key_signal_message

**Comment by Smattr** [comment]
As far as I can see, @dkonigsberg's changes don't affect functionality, they just remove an unused function parameter. The only explanation I can think of for this change causing the problems you're seeing is that you're compiling in a way where you include the old version of protocol.h but then link against the new library. This would result in calling `signal_message_verify_mac` with the wrong calling convention. I.e. passing a version number as the parameter libsignal expects to be `sender_identity_key`. But I don't see how dereferencing this value wouldn't segfault.

**Comment by sss123next** [comment]
yes, code this changes looks like not related, maybe i should create separated ticket for this problem.
for me situation is a bit unclear, firstly i thought that it's my bug, but here https://github.com/ChatSecure/ChatSecure-iOS/issues/743 i see exactly same behaviour as i have in my code now, so this may be upstream regression, but yes, this regression is not related for this ticket...

**Comment by chrisballinger** [comment]
@sss123next After a lot of debugging, I am pretty sure in our case this is being caused by an error with our SignedPreKey storage which was only storing one key at a time, so if the bundle was ever regenerated with a new SignedPreKey, all previous sessions would break. Still a lot of variables involved, so I'll update #65 with new findings as I go.
