### ISSUE TITLE
Can we have any Objective-C/ Swift wrapper SDK?

### ISSUE THREAD

**Issue by narendra-r** [WhisperSystems/libsignal-protocol-c#56]
Hi Team,
 We are trying to implement the signal-protocol but we can't find the Objective-C/Swift library for this. Can you help us to do this swift?

**Comment by moxie0** [comment]
Hey @narendra-r, thanks for getting in touch but we don't use GH issues for Q&A, support, or discussion. Check out the mailing list or the online forums for questions/discussion, and support@whispersystems.org for support.  Thanks.
