### ISSUE TITLE
Versioned library

### ISSUE THREAD

**Issue by jubalh** [WhisperSystems/libsignal-protocol-c#59]
I want to package this project for openSUSE.

Unfortunately I saw that you only create a .so file and don't seem to use [library versioning](https://autotools.io/libtool/version.html). Any reason for that? Could that be changed?

**Comment by dkonigsberg** [comment]
The most common use case for this library, as I'm currently aware, is to be statically linked into a larger application as part of that application's implementation of the Signal Protocol.  Dynamic linking has thus far been mostly an afterthought, and that is the reason not much work has been put into cleaning things up for that use case as of yet.

**Comment by jubalh** [comment]
I am packaging https://github.com/dino/dino for openSUSE too.
It also uses this library but checks it out of git. We would rather have libsignal packaged and then all programs using it only need to depend on it.

**Comment by dkonigsberg** [comment]
Understandable. I'll look into adding library versioning.  It may not exactly match the versioning of the Java library, but it'll hopefully be close enough.  (In other words, I'll likely keep it at v2.3.x until the few things the Java library changed/added in v2.4.0 are implemented.)
