### ISSUE TITLE
Provide signed releases

### ISSUE THREAD

**Issue by jubalh** [WhisperSystems/libsignal-protocol-c#60]
It would be great if you could [sign the tarballs](https://wiki.debian.org/Creating%20signed%20GitHub%20releases).

**Comment by dkonigsberg** [comment]
I don't have the ability to use a WhisperSystems private key for signing purposes, nor am I aware of an existing process for libsignal-protocol-java signed code distribution.
@moxie0 would have to comment on a request like this.

**Comment by moxie0** [comment]
Thanks but I don't think we're going to do this for now.
