### ISSUE TITLE
Is there any plan to make this library compatible for the android?

### ISSUE THREAD

**Issue by mjena** [WhisperSystems/libsignal-protocol-c#64]
Hi,
I know, for android, libsignal-protocol-java is available, but I am curious to know, if there is any plan for making this c-library compatible for android as well! 

regards,
MJ

**Comment by moxie0** [comment]
Hey @mjena I apologize but we don't use GitHub Issues for Q&A, just for tracking issues and bugs.  I've updated the issue template to reflect this, which I realize was missing before. If you're interested in questions or discussion, please see the mailing list or Signal forums. If you're interested in support, please see the support center. Thanks!

**Comment by mjena** [comment]
Dear @moxie0 thanks for the reply.
Can you please send me the link for the forum where I can ask or find answer for my above question?
