### ISSUE TITLE
is there any safe way to convert signal_buffer * to std::string object?

### ISSUE THREAD

**Issue by mjena** [WhisperSystems/libsignal-protocol-c#69]
Hi,

I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Bug description
currently I am using following way to convert from signal_buffer * to std::string:
std::string strMsg;
signal_buffer *eMsg = ciphertext_message_get_serialized(cipherMsg); // or some other function which returns signal_buffer *
retVal.assign((const char *)eMsg->data, eMsg->len);

and following way to convert std::string to signal_buffer *
std::string msg = "some text";
signal_buffer *eMsgBuf = signal_buffer_create((uint8_t *)msg.data(), msg.length());

while doing this conversion, I am facing few issues of not getting proper values in both directions.
e.g. session_cipher_decrypt_pre_key_signal_message() is failed after the above serialise call. 
Its possible that the conversion from uint8_t to char is creating the issue in my implementation.

So just wanted to know, if there is any safer way/method to convert signal_buffer* to std::string or char*!

Thanks,
MJ

**Comment by dkonigsberg** [comment]
Can you please post a more complete and correct code example that might actually compile, so I could attempt to reproduce your issue?

"std::string strMsg" is a stray declaration that is never used in the above code.

signal_buffer's "data" and "len" fields are never actually exposed by any public header.  They're typically accessed with the "signal_buffer_data()" and "signal_buffer_len()" helper functions.

**Comment by mjena** [comment]
My current code is tightly integrated in my project code, I will try to prepare a dummy code which you can compile and test on your side for this issue.
My main issue is I have to serialize the pre_key_bundle at one node and deserialize at other side.
But I could not find any viable function for serializing (pre_key_bundle to signal_buffer *) and deserializing (signal_buffer* to pre_key_bundle). Please let me know if there exist any such functions in the library.
So I am using my own serializer and deserializer which extracts each keys from pre_Key_Bundle and convert them into string and push it into a JSON object and pass that JSON to other side which deserialize and creates the PreKeyBundle again. But this preKeyBundle is now failing for session_cipher_decrypt_pre_key_signal_message() function. 
Kindly let me know, if there is any helper function in the library for this task.

**Comment by dkonigsberg** [comment]
The way `pre_key_bundle` is typically used, is as a container type for several pieces of information that are typically retrieved from an intermediary key server and then passed to `session_builder` to create a new session for encrypting an outgoing message. It makes more sense to handle this information directly, as the library does not directly handle serialization of these bundles.

**Comment by mjena** [comment]
thanks @dkonigsberg for all your help.
I could able to transfer the pre_key_bundle information by creating each of its member and putting them into a JSON individually and then transfer the JSON to other peer for creating the pre_key_bundle again and session_builder processing: it was a bit ugly but it works for me. ;)
