### ISSUE TITLE
no method to create a new ec_public_key

### ISSUE THREAD

**Issue by annerajb** [WhisperSystems/libsignal-protocol-c#75]
The ec_public_key structure is defined inside curve.c

It appears that the only way to obtain a ec_public_key is by generating one using the curve functions or loading from a store. 

How is the client suppose to load new ec_public_key received from a webserver? 
The structure is private so I cannot malloc it outside afaik.

**Comment by annerajb** [comment]
Hmm I think I found it? 
Am i suppose to use the curve_decode_point function to create it?

**Comment by dkonigsberg** [comment]
Yes, that's correct.  To create an `ec_public_key` from bytes, use the `curve_decode_point()` function.  (And for a private key, there's `curve_decode_private_point()`.  I apologize for the non-obvious naming, but these function names were directly converted from the Java library's `Curve.decodePoint()` and `Curve.decodePrivatePoint()`.

**Comment by annerajb** [comment]
Ok thank you.
