### ISSUE TITLE
Decrypt own messages

### ISSUE THREAD

**Issue by akawtia** [WhisperSystems/libsignal-protocol-c#76]
I have:
- [x] searched open and closed issues for duplicates

----------------------------------------

### Bug description
We are using https://github.com/WhisperSystems/libsignal-protocol-c/ in our chat application to encrypt messages end to end. We have an use case where we want to store encrypted messages on the server and retrieve them in the chat app.

In order to display the messages in the chat interface, we need to decrypt them. We are able to decrypt the messages the user received but not the messages which were sent by the user.

It is looking for the private key of the receiving user during decryption which is not available. Can you let us know if we are doing something wrong, can you help us resolve the issue.

**Comment by moxie0** [comment]
Hey @akawtia, sorry but we don't use GH issues for Q&A or support. If you have questions or are looking for discussion, the community forums are the best place. Thanks!
