### ISSUE TITLE
How to get serialized sender key distribution message?

### ISSUE THREAD

**Issue by ma11hew28** [WhisperSystems/libsignal-protocol-c#77]
After using `group_session_builder` to create a group session for sending messages, how do we get the serialized copy of the resulting `sender_key_distribution_message` so that we can send it to each member of the group?

In `protocol.h`, we see a function named `sender_key_message_get_ciphertext` but not one named `sender_key_distribution_message_get_ciphertext`.

Note: We posted [this question on the Open Whisper Systems Community discussion forum](https://whispersystems.discoursehosting.net/t/libsignal-protocol-c-how-to-get-serialized-sender-key-distribution-message/1192) but didn't get a response.

**Comment by dkonigsberg** [comment]
Answered on the discussion forum

**Comment by ma11hew28** [comment]
Thank you. Please see our [follow up question in our reply](https://whispersystems.discoursehosting.net/t/libsignal-protocol-c-how-to-get-serialized-sender-key-distribution-message/1192/4?u=ma11hew28).

> Once we get the serialized sender key distribution message, are we supposed to encrypt it the same way we would a regular two-party message (by using the `session_cipher_encrypt` function) for each address (recipient+device tuple) that's a part of the group? Then, should we send each encrypted sender key distribution message to the server, so that it can forward each encrypted sender key distribution message to the address for which it was encrypted?
