### ISSUE TITLE
Treat pairwise messages to multiple devices as group messages?

### ISSUE THREAD

**Issue by ma11hew28** [WhisperSystems/libsignal-protocol-c#80]
We posted the question [Treat pairwise messages to multiple devices as group messages? on the Open Whisper Systems Community discussion forum](https://whispersystems.discoursehosting.net/t/treat-pairwise-messages-to-multiple-devices-as-group-messages/1196) but didn't get a response.

> Could we implement messages sent to one user with multiple devices the same way as group messages?

**Comment by moxie0** [comment]
Hey @ma11hew28, please try not to open GH issues for questions. We don't use GitHub for Q&A, the best place for support is the online forums. Apologies if we can't always answer your questions immediately, we are a very small team and are pretty slammed. Thanks!
